import fs from 'node:fs';
import path from 'node:path';
import Database from 'better-sqlite3';
import { describe, expect, it } from 'vitest';

import { SCHEMA_SQL } from './db';

const SCHEMA_PATH = path.resolve(__dirname, '../../SCHEMA.txt');

const HEADER = `-- This file is auto-generated by src/server/schema.test.ts
-- Do not edit manually. To regenerate:
--   UPDATE_SCHEMA=true pnpm test src/server/schema.test.ts
`;

interface TableInfo {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

interface IndexListEntry {
  name: string;
  unique: number;
  origin: string;
}

interface IndexInfo {
  name: string;
}

interface ForeignKeyEntry {
  table: string;
  from: string;
  to: string;
  on_update: string;
  on_delete: string;
}

function generateSchema(): string {
  const db = new Database(':memory:');
  db.pragma('foreign_keys = ON');
  db.exec(SCHEMA_SQL);

  const tables = db
    .prepare(
      "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
    )
    .all() as { name: string }[];

  const sections: string[] = [];

  for (const { name: table } of tables) {
    const lines: string[] = [];
    lines.push(`TABLE: ${table}`);

    const columns = db
      .prepare(`PRAGMA table_info('${table}')`)
      .all() as TableInfo[];
    lines.push('  Columns:');
    for (const col of columns) {
      const parts = [`    ${col.name} ${col.type}`];
      if (col.pk) parts.push('PRIMARY KEY');
      if (col.notnull) parts.push('NOT NULL');
      if (col.dflt_value !== null) parts.push(`DEFAULT ${col.dflt_value}`);
      lines.push(parts.join(' '));
    }

    const fks = db
      .prepare(`PRAGMA foreign_key_list('${table}')`)
      .all() as ForeignKeyEntry[];
    if (fks.length > 0) {
      lines.push('  Foreign keys:');
      for (const fk of fks) {
        lines.push(
          `    ${fk.from} -> ${fk.table}(${fk.to}) ON DELETE ${fk.on_delete} ON UPDATE ${fk.on_update}`,
        );
      }
    }

    const indexes = db
      .prepare(`PRAGMA index_list('${table}')`)
      .all() as IndexListEntry[];
    const nonAutoIndexes = indexes.filter((idx) => idx.origin !== 'pk');
    if (nonAutoIndexes.length > 0) {
      lines.push('  Indexes:');
      for (const idx of nonAutoIndexes) {
        const idxCols = db
          .prepare(`PRAGMA index_info('${idx.name}')`)
          .all() as IndexInfo[];
        const colNames = idxCols.map((c) => c.name).join(', ');
        const unique = idx.unique ? ' UNIQUE' : '';
        lines.push(`    ${idx.name}${unique} (${colNames})`);
      }
    }

    sections.push(lines.join('\n'));
  }

  db.close();
  return `${HEADER}\n${sections.join('\n\n')}\n`;
}

describe('SCHEMA.txt', () => {
  it('matches the current database schema', () => {
    const generated = generateSchema();

    if (process.env.UPDATE_SCHEMA === 'true') {
      fs.writeFileSync(SCHEMA_PATH, generated, 'utf-8');
      return;
    }

    const existing = fs.existsSync(SCHEMA_PATH)
      ? fs.readFileSync(SCHEMA_PATH, 'utf-8')
      : '';
    expect(generated).toBe(existing);
  });
});
